plugins {
    alias libs.plugins.android.application
    alias libs.plugins.kotlin.android
    alias libs.plugins.kotlin.parcelize
}

android {
    compileSdk 37
    defaultConfig {
        applicationId "ca.apocrypher.webhelpdesk"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        resourceConfigurations += ['en']
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        viewBinding = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = "11"
    }
    namespace 'ca.apocrypher.webhelpdesk'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation libs.appcompat
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation libs.core.ktx

    // Parallelization Components
    implementation libs.kotlinx.coroutines.android
    implementation libs.kotlinx.coroutines.core

    // Preferences
    implementation libs.preference.ktx

    // API Support
    implementation libs.volley

    // Kotlin Nav Component
    implementation libs.navigation.fragment.ktx
    implementation libs.navigation.ui.ktx

    // Dynamic Feature Module Support
    implementation libs.navigation.dynamic.features.fragment

    // Testing Navigation
    androidTestImplementation libs.navigation.testing
    implementation libs.gson
    implementation libs.android.async.http
}
